spring:
  h2:
    console:
      enabled: true

  datasource:
    generate-unique-name: false
    name: db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  graphql:
    graphiql:
      enabled: true # graphiql을 통해 테스트 가능 여부 (localhost:8080/graphiql)
      printer:
        enabled: true # show-sql와 같이 graphql 콘솔에 쿼리 출력
    servlet:
      cors-enabled: true
      exception-handlers-enabled: true

  logging.level:
    org.hibernate.SQL: debug
